server:
  port: 7011


runEvn: '开发环境'


base:
  component:
    handler: true
#spring:
#  datasource:
#    username: root
#    password: 1234
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/dewen_examples?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    maxWait: 60000
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    connectionInitSqls: set names utf8mb3
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#  mvc:
#    view:
#      prefix: /
#      suffix: .jsp
#  devtools:
#    restart:
#      enabled: false
#
## mybaits-plus配置
#mybatis-plus:
#  # MyBatis Mapper所对应的XML文件位置
#  mapper-locations: classpath*:/mapper/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.dewen.mybatisplus.modules.entity
#  global-config:
#    # 关闭MP3.0自带的banner
#    banner: false
#    db-config:
#      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
#      id-type: auto
#      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#      field-strategy: 1
#      # 默认数据库表下划线命名
#      table-underline: true
#      # 逻辑删除配置
#      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
#      logic-delete-value: 1
#      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
#      logic-not-delete-value: 0
#    sql-parser-cache: true #开启 SQL 解析缓存注解生效
#  configuration:
#    map-underscore-to-camel-case: true
#    jdbc-type-for-null: 'NULL'
#tenant:
#  enable: false #默认关闭多租户功能，各服务根据需要开启
#  ignores: #不过滤tenantId的表,这里主要添加不包含tenant_id字段及全局表，表名统一用大写，否则无法识别
#    - test
