server:
  port: 8082
  servlet:
    context-path: /node2
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/dewen_anything?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: root
    druid:
      initial-size: 5

  redis:
    host: localhost
    database: 2
    port: 6379
    timeout: 6000
    password:
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 5
  data:
    mongodb:
      # 登录用户所在的数据库
      authentication-database: admin
      host: 192.168.111.144
      port: 27017
      database: test
      username: root
      password: root



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
