server:
  port: 8081
spring:
  application:
    name: provider
    #MQTT配置信息
  mqtt:
    #MQTT服务地址，端口号默认 11883，如果有多个，用逗号隔开
    url: tcp://192.168.111.144:1883
    #用户名
    username: admin
    #密码
    password: public
    #客户端id(不能重复)
    client:
      id: provider-001
    #MQTT默认的消息推送主题，实际可在调用接口是指定
    default:
      topic: dewen-topic
