server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(7vbo97d+WiweSao6OxN7hJwG5BCdwYqrUJzdZdxxe9vSIDfrXtc+kFuqC7H3D6y4nafrhtp/DfXoNDcBO2wgZswGgt0N2Ooc9fcvC1LdFfu0kjVS6fjENMOqTcEXpsHm2LPLtLnh+XFpbQKo44FS/yzlK/RLFFfD1uIdtpszanrF7vXtVoHdhw==)
    username: ENC(IkuUyvWnAm8u1Dz5TEfJPg==)
    password: ENC(5SkKVMCNR9Pl97D48Gmf4Q==)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    # if null not,如果为null 就会不展示改字段，反之展示
    # default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    time-zone: GMT+8

# key
jasypt:
  encryptor:
    password: Y6M9fAJQdU7jNp5MW