server:
  port: 8080
spring:
  # 数据库相关配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 这里加上后缀用来防止mysql乱码,serverTimezone=GMT%2b8设置时区
    url: ENC(ul0PHqbRRNne1AUFzT4lPECv0JJ4tQVyoCo3e/+Va5kIAmsfdi5C2qXabhxOmvCW6YtvQoDhHVPbOgbu6anT1uU0+7NyeLqal5SLEVo0ptIT/CxIhKrSJShGJF+tuED+1zmovSm4WEdzmuiTy9egthTUSgudM9fKihNDH5RceIsmy2oulGpM7w==)
    username: ENC(yS81qZ65y8Cq/8z/JzuUnw==)
    password: ENC(kzoFuZEcOG90EfK2Fp+oSQ==)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # 返回的api接口的配置，全局有效
  jackson:
    # 如果某一个字段为null，就不再返回这个字段
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    time-zone: GMT+8
# jasypt加密的密匙
jasypt:
  encryptor:
    password: Y6M9fAJQdU7jNp5MW