nacos:
  config:
    server-addr: 127.0.0.1:8848
    data-id: dewen2
    auto-refresh: true


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: *
