server:
  port: 8080
spring:
  application:
    name: consumer
  #MQTT配置信息
  mqtt:
    #MQTT服务端地址，端口默认为11883，如果有多个，用逗号隔开
    url: tcp://192.168.111.144:1883
    #用户名
    username: admin
    #密码
    password: public
    #客户端id（不能重复）
    client:
      id: consumer-001
    #MQTT默认的消息推送主题，实际可在调用接口时指定
    default:
      topic: dewen-topic

