server:
  port: 8080

spring:
  application:
    name: dewen-api-client
  jmx:
    enabled: true
  boot:
    admin:
      client:
        url: http://127.0.0.1:9090
        instance:
          service-url: http://127.0.0.1:${server.port}
          prefer-ip: true
          name: ${spring.application.name}
          # tel the server client's name and password
          metadata:
            user.name: dewen
            user.password: dewen
        username: dewen
        password: dewen
  security:
    user:
      name: dewen
      password: dewen

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: ${spring.application.name}.log
  pattern:
    file: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx'