server:
  port: 8080

netty:
  host: 127.0.0.1
  port: 9000
  path: /ws

spring:
  thymeleaf:
    cache: false
    checktemplatelocation: true
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:/static/
