mqtt:
  username: admin
  password: password
  # 你自己服务器的地址和端口，这个需要改
  host-url: tcp://127.0.0.1:8161
  # 这个改不改随意，但不同的客户端肯定不能一样
  clientID: test1
  # 默认主题
  default-topic: home/garden/fountain
  timeout: 100
  keepalive: 100

# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8088